# Generated by Django 5.2.17 on 2026-08-27 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cmsutils", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="imageupdates",
            name="failed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Failed at"),
        ),
        migrations.AlterField(
            model_name="imageupdates",
            name="approved_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Approved at"
            ),
        ),
        migrations.AlterField(
            model_name="imageupdates",
            name="approved_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="image_updates_approved_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Approved by",
            ),
        ),
    ]
