# Generated by Django 5.2.17 on 2026-09-07 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cmsutils", "0002_imageupdates_failed_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pageupdates",
            name="failed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Failed at"),
        ),
        migrations.AddField(
            model_name="pageupdates",
            name="log",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
